# Generated by Django 5.2.11 on 2026-02-12 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('shoplifting', 'Shoplifting Detection'), ('weapon', 'Weapon Detection'), ('balaclava', 'Balaclava/Mask Detection'), ('motion', 'Motion Detection'), ('custom', 'Custom Model')], max_length=50)),
                ('model_path', models.CharField(help_text='Path to model weights file', max_length=500)),
                ('confidence_threshold', models.FloatField(default=0.6)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'detection_models',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=50, unique=True)),
                ('max_cameras', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('shoplifting', 'Shoplifting Detected'), ('weapon', 'Weapon Detected'), ('balaclava', 'Balaclava/Mask Detected'), ('motion', 'Motion Detected'), ('multiple', 'Multiple Threats')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20)),
                ('detected_objects', models.JSONField(default=list, help_text='List of detected objects with confidence scores')),
                ('confidence_score', models.FloatField(help_text='Average confidence score')),
                ('frame_image', models.ImageField(help_text='Annotated frame with detected objects', upload_to='alerts/%Y/%m/%d/')),
                ('frame_timestamp', models.DateTimeField(help_text='When the frame was captured')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('webhook', 'Webhook')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='eyeguard.alert')),
            ],
            options={
                'db_table': 'alert_notifications',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('subscription_start_date', models.DateTimeField()),
                ('subscription_end_date', models.DateTimeField()),
                ('is_subscription_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eyeguard.subscription')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(help_text='Physical location of camera', max_length=255)),
                ('stream_url', models.CharField(help_text='RTSP/HTTP stream URL or video file path', max_length=500)),
                ('stream_type', models.CharField(choices=[('rtsp', 'RTSP Stream'), ('http', 'HTTP Stream'), ('file', 'Video File'), ('webcam', 'Webcam')], default='rtsp', max_length=20)),
                ('target_fps', models.IntegerField(default=10, help_text='Processing FPS (frames per second)')),
                ('motion_confidence', models.FloatField(default=0.6, help_text='Motion detection confidence threshold')),
                ('persist_frames', models.IntegerField(default=5, help_text='Frames to persist before triggering alert')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('error', 'Error')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='eyeguard.business')),
            ],
            options={
                'db_table': 'cameras',
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='eyeguard.camera'),
        ),
        migrations.CreateModel(
            name='CameraDetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.FloatField(blank=True, help_text='Override default model confidence threshold for this camera', null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyeguard.camera')),
                ('detection_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyeguard.detectionmodel')),
            ],
            options={
                'db_table': 'camera_detection_models',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='detection_models',
            field=models.ManyToManyField(related_name='cameras', through='eyeguard.CameraDetectionModel', to='eyeguard.detectionmodel'),
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('frames_processed', models.IntegerField(default=0)),
                ('alerts_generated', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('error', 'Error')], default='running', max_length=20)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='eyeguard.camera')),
            ],
            options={
                'db_table': 'processing_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='alerts_created_6327ec_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['camera', '-created_at'], name='alerts_camera__900726_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='alerts_status_5c7524_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cameradetectionmodel',
            unique_together={('camera', 'detection_model')},
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('business', 'name')},
        ),
    ]
