# Generated by Django 5.2.11 on 2026-02-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeguard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_queued_for_reprocess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_reprocessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='queued_for_reprocess_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='reprocess_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='reprocess_priority',
            field=models.IntegerField(default=5, help_text='1-10 priority for reprocessing (10=critical)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='frame_image',
            field=models.ImageField(help_text='Annotated frame with detected objects', upload_to=''),
        ),
    ]
