# Generated by Django 5.2.10 on 2026-02-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eyeguard", "0002_alert_is_queued_for_reprocess_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="camera_type",
            field=models.CharField(
                choices=[
                    ("generic", "Generic IP Camera"),
                    ("hikvision", "Hikvision"),
                    ("dahua", "Dahua"),
                    ("uniview", "Uniview"),
                    ("other", "Other"),
                ],
                default="generic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Camera password for authentication",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Camera username for authentication",
                max_length=255,
                null=True,
            ),
        ),
    ]
