# Generated by Django 5.2.10 on 2026-03-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eyeguard", "0003_camera_camera_type_camera_password_camera_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="channel",
            field=models.IntegerField(
                default=1,
                help_text="Camera channel number (for multi-channel DVRs, e.g., 1-32)",
            ),
        ),
    ]
